import "./../assets/css/globals.css";

export const metadata = {
  title: "Timer Flies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body className="h-screen w-screen bg-custom-gray-900">{children}</body>
    </html>
  );
}
