import { Contexts } from '../context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Contexts>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Contexts>
  );
}
